version: 2.1
jobs:
  cypress-run:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107-ff107
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Start app
          command: npm run start &
      - run:
          name: Run Cypress tests
          command: npx cypress run --browser chrome
workflows:
  test:
    jobs:
      - cypress-run
